name: TypeScript Lambda CI

on:
  pull_request:
    paths:
      - '**/*.ts'
jobs:
  typescript-lambda-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Assuming AWS Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Build TypeScript
        run: npm run build
      - name: Move Dependencies
        run: mv node_modules ./dist
      - name: Zip the build
        run: zip -r ./lambda_code.zip ./dist
      - name: s3 Lambda Artifact Creation
        run: |
          aws s3 cp ./lambda_code.zip s3://aws-s3-lambda-artifacts-use1-dev-dkkpwua/artifacts/lambda/${{ github.event.repository.name }}/
