name: Golang Lambda CI

on:
  pull_request:
    paths:
      - "**/*.go"
jobs:
  golang-lambda-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.20.x]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1
      # - name: Setup SSH Key
      #   uses: webfactory/ssh-agent@v0.8.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Golang Install
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build Golang Binary
        run: |
          cd src && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go && zip lambda_code.zip main
      - name: s3 Lambda Artifact Creation
        run: |
          aws s3 cp ./lambda_code.zip s3://aws-lambda-artifact-function-use1-dev/artifacts/lambda/${{ github.event.repository.name }}/
