name: Golang Lambda CI

on:
  pull_request:
    paths:
      - "**/*.go"
jobs:
  golang-lambda-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.5]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1
      - name: Golang Install
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build Golang Binary
        run: |
          cd src/main && go get && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build && zip ../../lambda_code.zip main
      - name: s3 Lambda Artifact Creation
        run: |
          aws s3 cp ./lambda_code.zip s3://aws-lambda-artifact-function-use1-dev/artifacts/lambda/${{ github.event.repository.name }}/
